### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by shacker** [Pawamoy/django-zxcvbn-password#31]
I found it a bit challenging to get the static media wired up. Even though the docs suggesting seeing the upstream repos for more information, they weren't super helpful either. 

So that staticfilesfinder can find the js assets, this must be added to INSTALLED_APPS:

`'zxcvbn_password',`

You refer to `form.media`, but that doesn't work because the example form in the docs doesn't have a `Media:` class. However, I think it's easier to just  include JS in the template:

```
{% load static %}
...
<script src="{% static 'zxcvbn_password/js/zxcvbn.js' %}"></script>
<script src="{% static 'zxcvbn_password/js/password_strength.js' %}"></script>
```

With that done, it started working but the indicator bar never changed color. Had to add to my css:

```
.progress-bar-warning {
    background-color: yellow;
}

.progress-bar-danger {
    background-color: red;
}

.progress-bar-success {
    background-color: green;
}
```

Finally, a little guidance on processing a valid password would be helpful (since we don't see Django's `set_password()` all that often:

```
        if form.is_valid():
            user = request.user
            user.set_password(form.cleaned_data['password1'])
            user.save()
```

I'll do a PR if you approve of the idea.

**Comment by Pawamoy** [comment]
Thanks for your report. Yes a PR would be much appreciated :) Please separate code and documentation in different PRs of course. Just came back from holidays, lot of work to catch up ^^

**Comment by shacker** [comment]
Hi -

I actually ended up doing a more manual implementation of zxcvbn rather than using this library. So since I'm not using it, am probably not the best person to do the PR after all. Should be an easy doc tweak though. Thanks!

**Comment by Pawamoy** [comment]
So, to get back at this:

- [x] doc about adding `zxcvbn_password` in `INSTALLED_APPS`: done thanks to @beruic 
- [ ] note about upstream docs: I will remove this note since it does not seem to be helpful
- [ ] note about `form.media`: I will update this note to be more clear: including `{{ form.media }}` in the JS block of your template will in fact include media from all form's fields and widgets. In this app, the only declared media is in the `PasswordStrengthInput` widget.
- [ ] colors not working: indeed the JS code relies on jquery and bootstrap :confused: I will add a note about these requirements in the README.
- [x] guidance about Django's `set_password`: it's an example among many others, I personally don't use `set_password`. Usually you just `User.objects.create(username=..., password=...)` with `username` and `password` retrieved from the form cleaned data.

**Comment by Pawamoy** [comment]
Thanks @shacker for your feedback!
